#!/bin/sh
#
# Proof of concept of the full pipeline. The existence of this script does not
# imply that shell script is a good language for writing compiler drivers.

set -ex

if [ $# -ne 1 ]; then
    exit "Usage: $0 FILE"
fi

REMORA_FILE=$1
FUT_FILE=${REMORA_FILE/.remora/.fut_soacs}
FUT_OPT_FILE=${REMORA_FILE/.remora/_opt.fut_soacs}
MLIR_FILE=${REMORA_FILE/.remora/.mlir}
MLIR_OPT_FILE=${REMORA_FILE/.remora/_opt.mlir}
LLVM_FILE=${REMORA_FILE/.remora/.ll}
SCAFFOLD_FILE=${REMORA_FILE/.remora/_scaffold.c}
EXE_FILE=${REMORA_FILE/.remora/}

remora futhark < "$REMORA_FILE" > "$FUT_FILE"

futhark dev -s "$FUT_FILE" > "$FUT_OPT_FILE"

mlir-backend "$FUT_OPT_FILE" > "$MLIR_FILE"

mlir-opt "$MLIR_FILE" \
  -one-shot-bufferize="bufferize-function-boundaries" \
  -buffer-deallocation-pipeline \
  -convert-scf-to-cf \
  -convert-cf-to-llvm \
  -finalize-memref-to-llvm \
  -convert-arith-to-llvm \
  -convert-func-to-llvm="use-bare-ptr-memref-call-conv=0" \
  -reconcile-unrealized-casts \
  -o "$MLIR_OPT_FILE"

mlir-translate --mlir-to-llvmir "$MLIR_OPT_FILE" -o "$LLVM_FILE"

clang "$LLVM_FILE" "$SCAFFOLD_FILE" -Wall -Wextra -o "$EXE_FILE"
